//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "content_proposal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub ip_address: String,
    pub created_at: DateTime,
    pub flagged: bool,
    pub model: String,
    #[sea_orm(column_type = "Text")]
    pub user_input: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub approved_at: Option<DateTime>,
    pub approved_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
