//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "content")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub created_at: DateTime,
    pub generating: bool,
    pub generation_started_at: Option<DateTime>,
    pub generation_finished_at: Option<DateTime>,
    pub flagged: bool,
    pub model: String,
    pub prompt_version: i32,
    pub fail_count: i32,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub image_id: Option<String>,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub user_input: String,
    pub view_count: i32,
    pub image_prompt: Option<String>,
    pub user_email: Option<String>,
    pub votes: i32,
    #[sea_orm(column_type = "Double")]
    pub hot_score: f64,
    pub generation_time_ms: Option<i32>,
    pub flarum_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub markdown: Option<String>,
    pub converted: bool,
    pub lemmy_id: Option<i32>,
    pub last_lemmy_post_attempt: Option<DateTime>,
    pub longview_count: i32,
    pub umami_view_count: i32,
    pub impression_count: i32,
    pub click_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_image::Entity")]
    ContentImage,
    #[sea_orm(has_many = "super::content_vote::Entity")]
    ContentVote,
}

impl Related<super::content_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentImage.def()
    }
}

impl Related<super::content_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentVote.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
