//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gpt_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub message: String,
    pub flagged: i8,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub response: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub error: Option<String>,
    pub tokens: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
