//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "history_generation_fail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub slug: String,
    pub created_at: DateTime,
    pub reason: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub exception: Option<String>,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")", nullable)]
    pub content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
