//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod content;
pub mod content_image;
pub mod content_proposal;
pub mod content_vote;
pub mod examples;
pub mod generation_schedule;
pub mod gpt_log;
pub mod history_generation_fail;
pub mod horde_log;
pub mod image_data;
pub mod language;
pub mod search_history;
pub mod translation;
