//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10
// supress warnings from sea-orm-codegen
#![allow(unused_imports)]
pub use super::content::Entity as Content;
pub use super::content_image::Entity as ContentImage;
pub use super::content_proposal::Entity as ContentProposal;
pub use super::content_vote::Entity as ContentVote;
pub use super::examples::Entity as Examples;
pub use super::generation_schedule::Entity as GenerationSchedule;
pub use super::gpt_log::Entity as GptLog;
pub use super::history_generation_fail::Entity as HistoryGenerationFail;
pub use super::horde_log::Entity as HordeLog;
pub use super::image_file::Entity as ImageFile;
pub use super::language::Entity as Language;
pub use super::search_history::Entity as SearchHistory;
pub use super::translation::Entity as Translation;
