//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::content::Entity as Content;
pub use super::content_image::Entity as ContentImage;
pub use super::examples::Entity as Examples;
pub use super::image_data::Entity as ImageData;
