const excuses = [
  "Our editors think it's a bad idea",
  "The Wibble staff politely declines",
  "Our satire generator just fainted",
  "The humor police vetoed that one",
  "Our jokesters are shaking their heads",
  "The satire gods disapprove",
  "Our comedy sensors just exploded",
  "The Wibble's ethics committee says no",
  "Our humorists are on strike for this one",
  "The satire fairy just vanished",
  "Our jesters are staging a protest",
  "The Wibble's moral compass is spinning",
  "Our comedy gurus advise against it",
  "The Wibble's humor code prohibits it",
  "Our satire specialists are cringing",
  "The Wibble's joke council disapproves",
  "Our humor committee is in tears",
  "The Wibble's satire sensors are on fire",
  "Our comedy experts are speechless",
  "The Wibble's jesters are in hiding",
  "Our humorists are holding their breath",
  "The satire squad has left the building",
  "Our comedy consultants are in shock",
  "The Wibble's joke jury says no",
  "Our humor panel is in disbelief",
  "The satire brigade is waving a white flag",
  "Our comedy connoisseurs are appalled",
  "The Wibble's humor tribunal objects",
  "Our jesters are pleading the fifth",
  "The satire assembly is in chaos",
  "Our comedy crew is in a frenzy",
  "The Wibble's humor board is speechless",
  "Our satire syndicate is in disarray",
  "The Wibble's joke alliance objects",
  "Our humor consortium is in a panic",
  "The satire collective comedy confederation is in distress",
  "The Wibble's humor coalition is in turmoil",
  "Our jesters are in a state of emergency",
  "The satire union is in a deadlock",
  "Our comedy corps is in a crisis",
  "The Wibble's humor task force is in chaos",
  "Our satire squadron is in a tailspin",
  "The Wibble's joke platoon is in a frenzy",
  "Our humor brigade is in a state of shock",
  "The satire division is in a standoff",
  "Our comedy battalion is in a stalemate",
  "The Wibble's humor regiment is in disarray",
  "Our jesters are in a state of confusion",
  "The satire fleet is in a state of panic",
  "Our comedy armada is in a state of alarm",
  "The Wibble's humor squadron is in a tizzy",
  "Our satire flotilla is in a state of disarray",
  "The Wibble's joke navy is in a state of chaos",
  "Our humor air force is in a state of shock",
  "The satire artillery is in a state of panic",
  "Our comedy infantry is in a state of alarm",
  "The Wibble's humor cavalry is in a state of confusion",
  "Our jesters are in a state of bewilderment",
  "The satire commandos are in a state of disarray",
  "Our comedy marines are in a state of chaos",
  "The Wibble's humor paratroopers are in a state of shock",
  "Our satire navy seals are in a state of panic",
  "The Wibble's joke rangers are in a state of alarm",
  "Our humor special forces are in a state of confusion",
  "The satire SWAT team is in a state of disarray",
  "Our comedy task force is in a state of chaos",
  "The Wibble's humor strike team is in a state of shock",
  "Our jesters are in a state of pandemonium",
  "The satire reconnaissance team is in a state of panic",
  "Our comedy intelligence unit is in a state of alarm",
  "The Wibble's humor espionage team is in a state of confusion",
  "Our satire surveillance team is in a state of disarray",
  "The Wibble's joke counterintelligence unit is in a state of chaos",
  "Our humor cyber warfare team is in a state of shock",
  "The satire psychological operations team is in a state of panic",
  "Our comedy electronic warfare team is in a state of alarm",
  "The Wibble's humor information operations team is in a state of confusion",
  "Our jesters are in a state of perplexity",
  "The satire civil affairs team is in a state of disarray",
  "Our comedy public affairs team is in a state of chaos",
  "The Wibble's humor medical team is in a state of shock",
  "Our satire logistics team is in a state of panic",
  "The Wibble's joke engineering team is in a state of alarm",
  "Our humor transportation team is in a state of confusion",
  "The satire maintenance team is in a state of disarray",
  "Our comedy supply team is in a state of chaos",
  "The Wibble's humor ordnance team is in a state of shock",
  "Our jesters are in a state of consternation",
  "The satire finance team is in a state of panic",
  "Our comedy personnel team is in a state of alarm",
  "The Wibble's humor administration team is in a state of confusion",
  "Our satire legal team is in a state of disarray",
  "The Wibble's joke chaplain team is in a state of chaos",
  "Our humor public safety team is in a state of shock",
  "The satire fire department is in a state of panic",
  "Our comedy police force is in a state of alarm",
  "The Wibble's humor security team is in a state of confusion",
];

const generatingMessages = [
  "Our monkeys are furiously typing away to create the perfect satire for you. Hold on!",
  "Just a moment, our team of comedic robots is putting the finishing touches on your article.",
  "Hang tight! We're just finishing up the world's most hilarious article for you.",
  "Don't worry, your satire is currently being cooked up by our humor chefs!",
  "Please wait while our team of undercover comedians secretly crafts your article.",
  "Your custom satire is being woven together by our skilled humor artisans. Stand by!",
  "Please wait as our comedic AI formulates the perfect punchline for your article.",
  "Hold on! Our team of satire specialists is working hard to bring you a masterpiece.",
  "Bear with us while our humor hamsters spin their wheels to generate your article.",
  "Our comedy alchemists are busy turning your URL into a barrel of laughs. Sit tight!",
  "Please be patient while our humor ninjas stealthily create your satire.",
  "We're currently inflating the whoopee cushion for your custom article. Stay tuned!",
  "Our humor engineers are constructing a comedy rollercoaster just for you. Hang on!",
  "Sit tight! Our team of satire scientists is hard at work synthesizing laughs for your article.",
  "Hold your horses! We're gathering the funniest ingredients to cook up your article.",
  "Please wait while we teach our humor bots the art of sarcasm for your article.",
  "Our comedy task force is working around the clock to bring you the wittiest article. Hang on!",
  "We're busy stirring the pot of hilarity to concoct your perfect satire. Just a moment!",
  "Hold on! We're currently training our humor parrots to squawk out your article.",
  "Just a moment! Our army of laughter engineers is assembling your article.",
  "We're currently squeezing the funniest jokes out of our humor juicer for your article. Stand by!",
  "Please be patient while our team of comedy wizards casts a spell on your article.",
  "Hold on! We're sending out our humor drones to gather laughs for your article.",
  "Please wait as we tickle our AI's funny bone to create your perfect satire.",
  "Our satire assembly line is working overtime to put together your article. Hang in there!",
  "Our humor machine is currently being oiled to produce your satire. Please stand by!",
  "Just a moment! We're summoning the comedy gods to bless your article.",
  "We're currently bottling up laughs to pour into your satire. Hold on!",
  "Hold on! We're busy knitting together the threads of humor for your article.",
  "We're just adding a pinch of hilarity to your satire. Hang tight!",
  "Please wait while our laughter factory churns out your custom article.",
  "We're busy navigating the sea of sarcasm to bring you the perfect satire. Hold on!",
  "Our humor miners are digging deep to unearth the funniest gems for your article.",
  "We're currently teaching our AI to juggle punchlines for your article. Hang on!",
  "Hold on! We're busy inflating the balloon of humor for your article.",
  "Please wait while we teleport your URL to the land of satire. We'll be right back!",
  "Our team of comedy detectives is busy solving the mystery of your perfect satire. Hang on!",
  "We're currently hunting for the wildest puns to include in your article. Stay tuned!",
  "Please wait as our humor rocket takes off to bring you the funniest satire from outer space.",
  "Hold on! We're busy polishing the gems of wit for your article.",
];

export function makeRandomExcuse() {
  return excuses[Math.floor(Math.random() * excuses.length)];
}

export function makeRandomGeneratingMessage() {
  return generatingMessages[
    Math.floor(Math.random() * generatingMessages.length)
  ];
}
